<?php declare(strict_types = 1);

// osfsl-/var/www/html/vendor/composer/../sentry/sentry-laravel/src/Sentry/Laravel/Console/TestCommand.php-PHPStan\BetterReflection\Reflection\ReflectionClass-Sentry\Laravel\Console\TestCommand
return \PHPStan\Cache\CacheItem::__set_state(array(
   'variableKey' => 'v2-6066375d0e86841018c9d2f1da436c36185f4112981e8d8f7997955f71189fa9-8.4.23-6.70.0.3',
   'data' => 
  array (
    'locatedSource' => 
    array (
      'class' => 'PHPStan\\BetterReflection\\SourceLocator\\Located\\LocatedSource',
      'data' => 
      array (
        'name' => 'Sentry\\Laravel\\Console\\TestCommand',
        'filename' => '/var/www/html/vendor/composer/../sentry/sentry-laravel/src/Sentry/Laravel/Console/TestCommand.php',
      ),
    ),
    'namespace' => 'Sentry\\Laravel\\Console',
    'name' => 'Sentry\\Laravel\\Console\\TestCommand',
    'shortName' => 'TestCommand',
    'isInterface' => false,
    'isTrait' => false,
    'isEnum' => false,
    'isBackedEnum' => false,
    'modifiers' => 0,
    'docComment' => NULL,
    'attributes' => 
    array (
    ),
    'startLine' => 20,
    'endLine' => 256,
    'startColumn' => 1,
    'endColumn' => 1,
    'parentClassName' => 'Illuminate\\Console\\Command',
    'implementsClassNames' => 
    array (
    ),
    'traitClassNames' => 
    array (
    ),
    'immediateConstants' => 
    array (
    ),
    'immediateProperties' => 
    array (
      'signature' => 
      array (
        'declaringClassName' => 'Sentry\\Laravel\\Console\\TestCommand',
        'implementingClassName' => 'Sentry\\Laravel\\Console\\TestCommand',
        'name' => 'signature',
        'modifiers' => 2,
        'type' => NULL,
        'default' => 
        array (
          'code' => '\'sentry:test {--transaction} {--dsn=}\'',
          'attributes' => 
          array (
            'startLine' => 22,
            'endLine' => 22,
            'startTokenPos' => 93,
            'startFilePos' => 512,
            'endTokenPos' => 93,
            'endFilePos' => 549,
          ),
        ),
        'docComment' => NULL,
        'attributes' => 
        array (
        ),
        'startLine' => 22,
        'endLine' => 22,
        'startColumn' => 5,
        'endColumn' => 66,
        'isPromoted' => false,
        'declaredAtCompileTime' => true,
        'immediateVirtual' => false,
        'immediateHooks' => 
        array (
        ),
      ),
      'description' => 
      array (
        'declaringClassName' => 'Sentry\\Laravel\\Console\\TestCommand',
        'implementingClassName' => 'Sentry\\Laravel\\Console\\TestCommand',
        'name' => 'description',
        'modifiers' => 2,
        'type' => NULL,
        'default' => 
        array (
          'code' => '\'Generate a test event and send it to Sentry\'',
          'attributes' => 
          array (
            'startLine' => 23,
            'endLine' => 23,
            'startTokenPos' => 102,
            'startFilePos' => 581,
            'endTokenPos' => 102,
            'endFilePos' => 625,
          ),
        ),
        'docComment' => NULL,
        'attributes' => 
        array (
        ),
        'startLine' => 23,
        'endLine' => 23,
        'startColumn' => 5,
        'endColumn' => 75,
        'isPromoted' => false,
        'declaredAtCompileTime' => true,
        'immediateVirtual' => false,
        'immediateHooks' => 
        array (
        ),
      ),
      'errorMessages' => 
      array (
        'declaringClassName' => 'Sentry\\Laravel\\Console\\TestCommand',
        'implementingClassName' => 'Sentry\\Laravel\\Console\\TestCommand',
        'name' => 'errorMessages',
        'modifiers' => 4,
        'type' => NULL,
        'default' => 
        array (
          'code' => '[]',
          'attributes' => 
          array (
            'startLine' => 30,
            'endLine' => 30,
            'startTokenPos' => 113,
            'startFilePos' => 760,
            'endTokenPos' => 114,
            'endFilePos' => 761,
          ),
        ),
        'docComment' => '/**
 * Buffer of error messages generated by the Sentry SDK.
 *
 * @var array
 */',
        'attributes' => 
        array (
        ),
        'startLine' => 30,
        'endLine' => 30,
        'startColumn' => 5,
        'endColumn' => 32,
        'isPromoted' => false,
        'declaredAtCompileTime' => true,
        'immediateVirtual' => false,
        'immediateHooks' => 
        array (
        ),
      ),
    ),
    'immediateMethods' => 
    array (
      'handle' => 
      array (
        'name' => 'handle',
        'parameters' => 
        array (
        ),
        'returnsReference' => false,
        'returnType' => 
        array (
          'class' => 'PHPStan\\BetterReflection\\Reflection\\ReflectionNamedType',
          'data' => 
          array (
            'name' => 'int',
            'isIdentifier' => true,
          ),
        ),
        'attributes' => 
        array (
        ),
        'docComment' => '/**
 * Execute the console command.
 *
 * @return int
 */',
        'startLine' => 37,
        'endLine' => 212,
        'startColumn' => 5,
        'endColumn' => 5,
        'couldThrow' => false,
        'isClosure' => false,
        'isGenerator' => false,
        'isVariadic' => false,
        'modifiers' => 1,
        'namespace' => 'Sentry\\Laravel\\Console',
        'declaringClassName' => 'Sentry\\Laravel\\Console\\TestCommand',
        'implementingClassName' => 'Sentry\\Laravel\\Console\\TestCommand',
        'currentClassName' => 'Sentry\\Laravel\\Console\\TestCommand',
        'aliasName' => NULL,
      ),
      'generateTestException' => 
      array (
        'name' => 'generateTestException',
        'parameters' => 
        array (
          'command' => 
          array (
            'name' => 'command',
            'default' => NULL,
            'type' => 
            array (
              'class' => 'PHPStan\\BetterReflection\\Reflection\\ReflectionNamedType',
              'data' => 
              array (
                'name' => 'string',
                'isIdentifier' => true,
              ),
            ),
            'isVariadic' => false,
            'byRef' => false,
            'isPromoted' => false,
            'attributes' => 
            array (
            ),
            'startLine' => 217,
            'endLine' => 217,
            'startColumn' => 46,
            'endColumn' => 60,
            'parameterIndex' => 0,
            'isOptional' => false,
          ),
          'arg' => 
          array (
            'name' => 'arg',
            'default' => NULL,
            'type' => 
            array (
              'class' => 'PHPStan\\BetterReflection\\Reflection\\ReflectionNamedType',
              'data' => 
              array (
                'name' => 'array',
                'isIdentifier' => true,
              ),
            ),
            'isVariadic' => false,
            'byRef' => false,
            'isPromoted' => false,
            'attributes' => 
            array (
            ),
            'startLine' => 217,
            'endLine' => 217,
            'startColumn' => 63,
            'endColumn' => 72,
            'parameterIndex' => 1,
            'isOptional' => false,
          ),
        ),
        'returnsReference' => false,
        'returnType' => 
        array (
          'class' => 'PHPStan\\BetterReflection\\Reflection\\ReflectionNamedType',
          'data' => 
          array (
            'name' => 'Exception',
            'isIdentifier' => false,
          ),
        ),
        'attributes' => 
        array (
        ),
        'docComment' => '/**
 * Generate an example exception to send to Sentry.
 */',
        'startLine' => 217,
        'endLine' => 225,
        'startColumn' => 5,
        'endColumn' => 5,
        'couldThrow' => false,
        'isClosure' => false,
        'isGenerator' => false,
        'isVariadic' => false,
        'modifiers' => 2,
        'namespace' => 'Sentry\\Laravel\\Console',
        'declaringClassName' => 'Sentry\\Laravel\\Console\\TestCommand',
        'implementingClassName' => 'Sentry\\Laravel\\Console\\TestCommand',
        'currentClassName' => 'Sentry\\Laravel\\Console\\TestCommand',
        'aliasName' => NULL,
      ),
      'logErrorMessageFromSDK' => 
      array (
        'name' => 'logErrorMessageFromSDK',
        'parameters' => 
        array (
          'message' => 
          array (
            'name' => 'message',
            'default' => NULL,
            'type' => 
            array (
              'class' => 'PHPStan\\BetterReflection\\Reflection\\ReflectionNamedType',
              'data' => 
              array (
                'name' => 'string',
                'isIdentifier' => true,
              ),
            ),
            'isVariadic' => false,
            'byRef' => false,
            'isPromoted' => false,
            'attributes' => 
            array (
            ),
            'startLine' => 227,
            'endLine' => 227,
            'startColumn' => 44,
            'endColumn' => 58,
            'parameterIndex' => 0,
            'isOptional' => false,
          ),
        ),
        'returnsReference' => false,
        'returnType' => 
        array (
          'class' => 'PHPStan\\BetterReflection\\Reflection\\ReflectionNamedType',
          'data' => 
          array (
            'name' => 'void',
            'isIdentifier' => true,
          ),
        ),
        'attributes' => 
        array (
        ),
        'docComment' => NULL,
        'startLine' => 227,
        'endLine' => 230,
        'startColumn' => 5,
        'endColumn' => 5,
        'couldThrow' => false,
        'isClosure' => false,
        'isGenerator' => false,
        'isVariadic' => false,
        'modifiers' => 1,
        'namespace' => 'Sentry\\Laravel\\Console',
        'declaringClassName' => 'Sentry\\Laravel\\Console\\TestCommand',
        'implementingClassName' => 'Sentry\\Laravel\\Console\\TestCommand',
        'currentClassName' => 'Sentry\\Laravel\\Console\\TestCommand',
        'aliasName' => NULL,
      ),
      'clearErrorMessagesFromSDK' => 
      array (
        'name' => 'clearErrorMessagesFromSDK',
        'parameters' => 
        array (
        ),
        'returnsReference' => false,
        'returnType' => 
        array (
          'class' => 'PHPStan\\BetterReflection\\Reflection\\ReflectionNamedType',
          'data' => 
          array (
            'name' => 'void',
            'isIdentifier' => true,
          ),
        ),
        'attributes' => 
        array (
        ),
        'docComment' => NULL,
        'startLine' => 232,
        'endLine' => 235,
        'startColumn' => 5,
        'endColumn' => 5,
        'couldThrow' => false,
        'isClosure' => false,
        'isGenerator' => false,
        'isVariadic' => false,
        'modifiers' => 4,
        'namespace' => 'Sentry\\Laravel\\Console',
        'declaringClassName' => 'Sentry\\Laravel\\Console\\TestCommand',
        'implementingClassName' => 'Sentry\\Laravel\\Console\\TestCommand',
        'currentClassName' => 'Sentry\\Laravel\\Console\\TestCommand',
        'aliasName' => NULL,
      ),
      'printDebugTips' => 
      array (
        'name' => 'printDebugTips',
        'parameters' => 
        array (
        ),
        'returnsReference' => false,
        'returnType' => 
        array (
          'class' => 'PHPStan\\BetterReflection\\Reflection\\ReflectionNamedType',
          'data' => 
          array (
            'name' => 'void',
            'isIdentifier' => true,
          ),
        ),
        'attributes' => 
        array (
        ),
        'docComment' => NULL,
        'startLine' => 237,
        'endLine' => 255,
        'startColumn' => 5,
        'endColumn' => 5,
        'couldThrow' => false,
        'isClosure' => false,
        'isGenerator' => false,
        'isVariadic' => false,
        'modifiers' => 4,
        'namespace' => 'Sentry\\Laravel\\Console',
        'declaringClassName' => 'Sentry\\Laravel\\Console\\TestCommand',
        'implementingClassName' => 'Sentry\\Laravel\\Console\\TestCommand',
        'currentClassName' => 'Sentry\\Laravel\\Console\\TestCommand',
        'aliasName' => NULL,
      ),
    ),
    'traitsData' => 
    array (
      'aliases' => 
      array (
      ),
      'modifiers' => 
      array (
      ),
      'precedences' => 
      array (
      ),
      'hashes' => 
      array (
      ),
    ),
  ),
));